### ISSUE TITLE
docs: update insturctions to show to join the running network

### ISSUE THREAD

**Issue by marbar3778** [osmosis-labs/networks#84]
Update joining as a validator as well

**Comment by daniel-farina** [comment]
I'm assigning this to myself. I encountered several issues when running a full node, also the node list seems outdated and so far I was not able to connect any node.

Items to mark this ticket as closed:
- Explain how to run a full node
- test and make sure we have a good way of keeping seed nodes updated

I created a separate task to track, document and test the latest to join as a validator node.
